# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-17 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('column', models.CharField(max_length=20)),
                ('publish_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
