# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish_time', 'title')},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('id', 'slug')]),
        ),
    ]
