# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_auto_20181017_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='column',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_Column', to='BlogPost.Column'),
        ),
    ]
