# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_auto_20181017_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
