# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0006_auto_20181018_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_time', 'title')},
        ),
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
