# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0007_auto_20181020_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
