# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0008_auto_20181023_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='column',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Pospt_Column', to='BlogPost.Column'),
        ),
    ]
