# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-26 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPost', '0010_post_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='artilces_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
