# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181023_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-comment_time',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
