# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20181024_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
